option(${PROJECT_NAME}_USE_GFLAGS "Download gflags" ON)
option(${PROJECT_NAME}_USE_GLOG "Download glog" ON)
option(${PROJECT_NAME}_USE_GSL "Download glog" ON)
option(${PROJECT_NAME}_USE_GOOGLETEST "Download google test" ON)
option(${PROJECT_NAME}_USE_PROTOBUFS "Download google protocol buffers lib" ON)
option(${PROJECT_NAME}_USE_CARES "Download cares lib" ON)
option(${PROJECT_NAME}_USE_GRPC "Download grpc lib" ON)
option(BUILD_TESTING "" OFF)
option(RE2_BUILD_TESTING "" OFF)
option(MPLReg_ENABLE_TESTS "Compile and run registry unit tests" ON)
option(mpmc_ring_ENABLE_TESTS "Compile and run registry unit tests" ON)
option(spring_ENABLE_TESTS "Compile and run spring unit tests" ON)
option(extractor_ENABLE_TESTS "Compile and run extractor unit tests" ON)
